version: '3.7'
services:
  dbs-back-end:
    image: webapp-dbs-back-end:latest
    network_mode: "host"
    volumes:
      - "/home/lucatognazzi/projects/webapp-dbs/back-end:/home/node/app"
      - "/home/node/app/node_modules"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5432:5432"
    command:
      [ "yarn", "start:dev" ]
  dbs-front-end:
    image: webapp-dbs-front-end:latest
    network_mode: "host"
    volumes:
      - "/home/lucatognazzi/projects/webapp-dbs/front-end:/home/node/app"
      - "/home/node/app/node_modules"
    command:
      [ "yarn", "dev" ]

